apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/akhtarmoin07/azure-platform-lab-gitops.git
    targetRevision: main
    path: platform/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ServerSideApply=true
  revisionHistoryLimit: 10
